ENV: prd

DATABASES:
  default:
    ENGINE: {{cookiecutter.project}}.config.db.backends.customer_mysql
    NAME: {{cookiecutter.project}}
    USER: root
    PASSWORD: MyNewPass4!
    HOST: localhost
    PORT: 3306
    OPTIONS:
      charset: utf8mb4


CELERY_BROKER_URL: amqp://admin:admin@localhost:5672/ci

MEDIA_ROOT: /data/upload
STATIC_ROOT: /data/web/{{cookiecutter.project}}_static

DEBUG: false
