ENV: prd

DATABASES:
  default:
    ENGINE: {{cookiecutter.project}}.config.db.backends.customer_mysql
    NAME: {{cookiecutter.project}}
    USER: root
    PASSWORD: "123456"
    HOST: mysql
    PORT: 3306
    OPTIONS:
      charset: utf8mb4

DEBUG: false
