ENV: dev

DATABASES:
  default:
    ENGINE: {{cookiecutter.project}}.config.db.backends.customer_mysql
    NAME: {{cookiecutter.project}}
    USER: root
    PASSWORD:
    HOST: 127.0.0.1
    PORT: 3306
    OPTIONS:
      charset: utf8mb4

