ENV: uat1

DATABASES:
  default:
    ENGINE: django.db.backends.mysql
    NAME: {{cookiecutter.project}}
    USER: root
    PASSWORD:
    HOST: 127.0.0.1
    PORT: 3306


CELERY_BROKER_URL: amqp://admin:admin@localhost:5672/ci

MEDIA_ROOT: /data/upload
STATIC_ROOT: /data/web/{{cookiecutter.project}}_static
