# Generated by Django 2.2.3 on 2019-07-14 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import model_utils.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOpenid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('openid_id', models.CharField(max_length=512, verbose_name='OpenID')),
                ('openid_type', models.IntegerField(choices=[[1, 'phone'], [2, 'email']], verbose_name='openid类型')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_openid', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, model_utils.managers.SoftDeletableManager),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='手机号')),
                ('real_name', models.CharField(blank=True, max_length=150, verbose_name='真实姓名')),
                ('sex', models.IntegerField(choices=[[0, 'female'], [1, 'make'], [2, 'unknown']], default=2, verbose_name='性别')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
