# Generated by Django 2.2.3 on 2019-07-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useropenid',
            unique_together={('openid_type', 'openid_id')},
        ),
    ]
