# Generated by Django 2.2.3 on 2019-07-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190714_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='useropenid',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
