# Generated by Django 2.2.3 on 2019-07-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190725_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useropenid',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='useropenid',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='软删除标志'),
        ),
    ]
